# Sample config for Hermes model training

dataset:
  path: ../../datasets/kits23_IL/phase3_dataset.yaml
  num_classes: 3
  patch_size: [128, 128, 128]

training:
  epochs: 100
  batch_size: 2
  learning_rate: 0.0001
  optimizer: AdamW
  amp: True

model:
  name: hermes
  architecture: hermes
  input_channels: 1
  dimension: 3D

logging:
  save_dir: logs/phase3
  experiment_name: phase3_run
